Feature/readme
Cactu5/recruitment-application pull request #17
Opened 2021-02-15 13:15 UTC by Mechakhan

2021-02-20 17:29 UTC, Mechakhan commented on README.md
> + - **maven**: ?
@FilipKTH would you like to share how you compile the application or should we skip it?

2021-02-22 10:35 UTC, FilipKTH commented on README.md
> + - **maven**: ?
I use the standard maven commands to run the jar and run the tests. It's also independent of the IDE:

**Tests**
`mvn test`
**Run**
`mvn spring-boot:run`

2021-02-22 12:48 UTC, Mechakhan commented on README.md
> + - **maven**: ?
Fixed! Is this branch ready for merge?

2021-02-22 13:02 UTC, Cactu5 requested changes

2021-02-22 13:02 UTC, Cactu5 commented on CONTRIBUTING.md
> +must be a test source file for each source file, and it should test both invalid and valid inputs
"... a test source file for each source file ..." seems too specific, maybe something like "Test all public methods, except for simple getters and setters."?

2021-02-22 13:02 UTC, Cactu5 commented on README.md
> +                      spring's mockMVC to simulate HTTP transactions.
I think "each source file" is a bit too much, maybe something like "Test all public methods, except for simple getters and setters."?

2021-02-22 13:24 UTC, Mechakhan commented on CONTRIBUTING.md
> +must be a test source file for each source file, and it should test both invalid and valid inputs
It has been done, opinions?

2021-02-22 13:26 UTC, Cactu5 approved these changes

2021-02-22 13:31 UTC, merged